[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*


addopts = 
    -v
    --tb=short
    
#Маркеры
markers =
    smoke: Быстрые smoke-тесты
    regression: Полные regression-тесты
    ui: UI тесты
    content: Тесты содержания