[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

#Отчеты
addopts = 
    -v
    --tb=short
    --strict-markers
    --html=reports/report.html
    --self-contained-html
    --junitxml=reports/junit.xml

#Маркеры
markers =
    smoke: Быстрые smoke-тесты
    regression: Полные regression-тесты
    ui: UI тесты
    content: Тесты содержания